project:
	gcc -g -o project project.c die_with_error.c -lpthread
p:
	gcc -g -o p p2.c die_with_error.c -lpthread
sjf:
	gcc -g -o sjf nonPremptiveSJF.c die_with_error.c 

sjf2:
	gcc -g -o sjf2 preemptiveSJF.c die_with_error.c
fcfs:
	gcc -g -o fcfs FCFS.c die_with_error.c

clean:
	rm sjf sjf2 fcfs
